import os
import time
print("")
print("")
time.sleep(0.1)
print("                            ___ ______________.____   __________ ")
time.sleep(0.1)
print("                           /   |   \_   _____/|    |  \______   |")
time.sleep(0.1)
print("                          /    ~    \    __)_ |    |   |     ___/")
time.sleep(0.1)
print("                          \    Y    /        \|    |___|    |    ")
time.sleep(0.1)
print("                           \___|_  /_______  /|_______ \____|    ")
time.sleep(0.1)
print("                                 \/        \/         \/         ")
print("")
print("")
print("                            How to use this tool? It's very simple")
time.sleep(0.1)
print("")
time.sleep(0.1)
print("")
print("")
time.sleep(0.1)
print("                1. To use IP Tracker : open [IP Tracker tutoriel.txt] in tutoriel")
time.sleep(0.1)
print("")
print("                2. To use IP pinger  : open [IP Pinger tutoriel.txt] in tutoriel")
print("")
print("")
print("")

choice = input("Press [6] to return to the menu :")

if choice == '6':
    os.system("python prgrm/start.py")